### ISSUE TITLE
[WIP] Fix examples in README

### ISSUE THREAD

**Issue by KrzysztofKarol** [MichalZalecki/mappet#16]
Some examples in [README](https://github.com/MichalZalecki/mappet/blob/master/README.md) e.g.:
```javascript
const schema = {
  last_name: ["last_name", str => str.toUpperCase()],
};
```
are not working.

**Comment by MichalZalecki** [comment]
Thanks! It applied to the previous version. You're adding `[WIP]` to indicate you're going to make a PR?

**Comment by KrzysztofKarol** [comment]
Yes

**Comment by MichalZalecki** [comment]
Fixed with https://github.com/MichalZalecki/mappet/commit/4fcf634425d1895ba45ee6ff071647c7f80463c8
