### ISSUE TITLE
Question: reverse a schema

### ISSUE THREAD

**Issue by bytewiz** [MichalZalecki/mappet#3]
is it possible to reverse the scheme for a mapper e.g.

## Description
```
const source = {
   data: {
      entity: {
        key: 'someKey'
      },
      person: {
        firstname: 'someName'
      }
   }
}
```
```
const someMapper = mappet([
  ['key', 'data.entitiy.key'],
  ['name', 'data.person.firstname'],
])

```
```
result of someMapper(source)
{
  key: 'someKey'
  name: 'someName'
}
```
## The "problem"
I want to reverse transform the object for it to send to the backend,
Is this possible without creating a scheme that is opposite with a function like:
```
someMapper(source, reverse)
or
reverse(someMapper(source))
```

I assume this is not part of the current API for this but just curious

**Comment by MichalZalecki** [comment]
@bytewiz That's interesting, thanks for creating this issue. I'm used to creating 2nd mapper for that which might be not optimal but it's easier for people to understand the transformation. I'm only concerned what should happen with 3rd and 4th parameter e.g. if you map table to object with `reduce` or omit a property.

**Comment by bytewiz** [comment]
@MichalZalecki thanks, makes sense! I was just curious to how you would go about that, but I also like the explicit way of just having 2 mappers
