### ISSUE TITLE
Consider importing lodash differently?

### ISSUE THREAD

**Issue by bytewiz** [MichalZalecki/mappet#4]
When checking the source code after having been notified by my build analyzer that lodash is required in this npm module. 

I saw that lodash is imported like this: https://github.com/MichalZalecki/mappet/blob/master/src/lib/mappet.ts#L1

Which as far as I am aware this will include the entire lodash lib. (unless you have some sort of loader to cherry pick the functions for you)

Please correct me if I am wrong!

but according to the docs. from lodash it looks like they suggest importing like so aswell

![image](https://user-images.githubusercontent.com/16811871/28354249-78cc8d64-6c5f-11e7-832a-04e5f86b43c5.png)

before:
```
import { get, set, clone } from 'lodash';
```

after:
```
import get from 'lodash/get';
import set from 'lodash/set';
import clone from 'lodash/clone';
```

Thoughts one this? 👍 

If you agree, I can do a PR

**Comment by MichalZalecki** [comment]
> Please correct me if I am wrong!

@bytewiz No, you are right! Although library isn't bundling lodash within its source it `require`s entire lodash so the application bundle will have it.

> If you agree, I can do a PR

Please, do!

Ideally I'd like to keep one import statement, target es modules with TS and use rollup. I've tried once but results were less than satisfying. I feel like separate imports are the best option ATM.

**Comment by bytewiz** [comment]
#5 please review the PR and see if you are happy with the suggested solution 👍  thanks
